### ISSUE TITLE
Cannot import: No valid ZIP archive

### ISSUE THREAD

**Issue by ThomasMeschke** [CubeIR/trulyVanillaRTX#1]
I downloaded the last version from January 22nd.
 When launching, Minecraft tries to import the pack but fails with the notice "Not a valid zip archive". 
See attached screenshot. 
![ImportError](https://user-images.githubusercontent.com/15939458/105630371-19003680-5e49-11eb-9e08-227943f49f92.png)

**Comment by CubeIR** [comment]
Fixed.
